<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>source.oberon2</string>
	<key>patterns</key>
	<array>
		<dict>
        	<key>match</key>
			<string>\b(AND|ARRAY|BEGIN|BY|CASE|CONST|DIV|DO|ELSE|ELSIF|END|EXIT|FOR|IF|IMPORT|IS|IN|LOOP|MOD|MODULE|NOT|OF|OR|POINTER|PROCEDURE|RECORD|REPEAT|RETURN|THEN|TO|TYPE|UNTIL|VAR|WITH|WHILE)\b</string>
        	<key>name</key>
        	<string>keyword.oberon2</string>
      	</dict>
		<dict>
        	<key>match</key>
			<string>\b(DEFINITION|EXPORT|IMPLEMENTATION|QUALIFIED|CARDINAL|LONGCARD|SHORTCARD)\b</string>
        	<key>name</key>
        	<string>keyword.other.oberon2</string>
      	</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.oberon2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(PROCEDURE)\b\s+(\(.*?\))(\:\s+\w*)?\s*</string>
			<key>name</key>
			<string>meta.function.oberon2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(IN|IS|DIV|MOD|AND|OR|\#)\b</string>
			<key>name</key>			
			<string>keyword.operator.oberon2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SET|BITSET|INTEGER|LONGLONGINT|LONGINT|SHORTINT|BOOLEAN|REAL|LONGREAL|SHORTREAL|CHAR)\b</string>
			<key>name</key>			
			<string>storage.support.type.oberon2</string>
		</dict>
		<dict>
        	<key>match</key>
			<string>\b(ABS|ASSERT|ASH|CAP|CHR|COPY|DEC|DISPOSE|ENTIER|EXCL|HALT|INC|INCL|LEN|LENGTH|LONG|MAX|MIN|NEW|ODD|ORD|SHORT|SIZE)\b</string>
			<key>name</key>
        	<string>support.function.oberon2</string>
      	</dict>
		<dict>
			<key>match</key>
			<string>\b(TRUE|FALSE|NIL)\b</string>
			<key>name</key>
			<string>constant.language.oberon2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9a-fA-F]+)X|([0-9]+)C)\b</string>
			<key>name</key>
			<string>string.other.oberon2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9a-fA-F]+)H\b</string>
			<key>name</key>
			<string>constant.numeric.hex.oberon2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)|(\d*\.\d+([DE][\-+]?\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.oberon2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\<\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.oberon2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\></string>
			<key>name</key>
			<string>comment.block.oberon2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.oberon2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.oberon2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.oberon2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oberon2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oberon2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.oberon2.one</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oberon2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oberon2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.oberon2.two</string>
		</dict>
	</array>
</dict>
</plist>